name: Zip Files

on: 
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
      - name: Create directory
        run:
          mkdir build
      - name: Create artifact
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -X -r build/paypalfeecalculator.zip . -x zip** build** *.git* *.md .replit Archiv.zip index.html
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: build/paypalfeecalculator.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
