- name: Easy Zip Files
  uses: vimtor/action-zip@v1

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: dist/ manifest.json
          dest: result.zip
