name: Zip Files

on: 
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3
      - name: Create directory
        run:
          mkdir build
      - name: Create artifact
        uses: montudor/action-zip@v1.0.0
        with:
          args: zip -X -r build/paypalfeecalculator.zip . -x zip** build** *.git* *.md .replit Archiv.zip index.html
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: build/paypalfeecalculator.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish new version
        uses: Klemensas/chrome-extension-upload-action@master
        with:
          refresh-token: '${{ secrets.REFRESH_TOKEN }}'
          client-id: '${{ secrets.CLIENT_ID }}'
          client-secret: '${{ secrets.CLIENT_SECRET }}'
          file-name: 'build/paypalfeecalculator.zip'
          app-id: '${{ secrets.APP_ID }}'
          publish: true
