name: Zip Files

on: workflow_dispatch

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: images/ manifest.json
          recursive: true
          dest: result.zip
