name: Zip Files

on: workflow_dispatch

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
      - name: Create artifact
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -X -r build/extension.zip . -x zip/\* *.git* *.md .replit
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
            name: PayPalFeeCalculator
            path: build/extension.zip
