name: Zip Files

on: workflow_dispatch

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: images/ manifest.json Screenshot.png popup.html popup.js w2ui-1.5.min.css w2ui-1.5.min.js
          recursive: true
          dest: extension.zip
      - uses: actions/upload-artifact@v1
        with:
        name: my-artifact
        path: ${{ github.workspace }}/zip/extension.zip
